name: CICD Pipeline1

on:
  push:
    branches: 
      - dev
      - qa
      - main
      - prod

jobs:
  dummytest:
    runs-on: self-hosted
    steps:
    
    - name: Configure AWS Credentials
      uses: actions/checkout@v2
    - name: Compile
      run: echo "Hi"
      
 
  deploy_to_prod:
    runs-on: self-hosted
    if: github.event.ref == 'refs/heads/prod'
    needs: [dummytest]
    environment:
      name: prod
    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
        
    - name: Log in to Amazon ECR 
      uses: aws-actions/amazon-ecr-login@v1
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name eks-cluster --region us-east-1
    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.EKS_KUBECONFIG }}" > $HOME/.kube/config
        
    - name: Deploy springboot microservice
      env:
          SPRINGBOOT_APP_IMAGE: ${{ secrets.SPRINGBOOT_APP_IMAGE }}
          IMAGE_TAG: "bankapp-springboot-image-de923544e076328c17dce3f3c068543ec846078f"
      run: |
        kubectl set image deployment/bankapp bankapp=$SPRINGBOOT_APP_IMAGE:$IMAGE_TAG --namespace prod



  
  deploy_to_dev:
    runs-on: self-hosted
    if: github.event.ref == 'refs/heads/dev'
    needs: [dummytest]
    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
        
    - name: Log in to Amazon ECR 
      uses: aws-actions/amazon-ecr-login@v1
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name eks-cluster --region us-east-1
    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.EKS_KUBECONFIG }}" > $HOME/.kube/config
        
    - name: Deploy springboot microservice
      env:
          SPRINGBOOT_APP_IMAGE: ${{ secrets.SPRINGBOOT_APP_IMAGE }}
          IMAGE_TAG: "bankapp-springboot-image-de923544e076328c17dce3f3c068543ec846078f"
      run: |
        kubectl set image deployment/bankapp bankapp=$SPRINGBOOT_APP_IMAGE:$IMAGE_TAG --namespace dev
