name: CICD Pipeline

on:
  push:
    branches: 
      - dev
      - qa
      - main
      - prod

jobs:
  
  deploy_to_kubernetes:
    runs-on: self-hosted
    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
        
    - name: Log in to Amazon ECR 
      uses: aws-actions/amazon-ecr-login@v1
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name eks-cluster --region us-east-1
    - name: Deploy springboot microservice
      run: |
        kubectl apply -f ds.yml --namespace prod
